module.exports = Object.freeze({
    MAX_USED_MEM_PERCENTAGE: 100,
    CONVERSION_TO_PERCENTAGE: 100,
    TIME_TO_RECALCULATE_DATA: 500,
    TIME_TO_WAIT_FOR_CPU: 1000,
    MAX_NUMBERS_AFTER_POINT: 2,
    EXIT_KEY: 'Ctrl+C'
});